### ISSUE TITLE
deltaX bug in Power Spectrum Plotting Function

### ISSUE THREAD

**Issue by PetchMa** [jobovy/streamgap-pepper#8]
# Issue
Issue with `plot_power` function where the binning appears incorrect. Where the `DeltaX` appears to be off by order `N` in the power spectrum. In `pepper_calc.py` line `179`.

# Reproduce
Environment: 
```
python == 3.11.5
Numpy ==1.25
```
Example code uses a modified version of [line](https://github.com/jobovy/streamgap-pepper/blob/176c8f67abf322a6a924a9e7757a004733a7413a/pepper_calc.py#L179C35-L179C35) shows a peak at the wrong frequency after inputing a known distribution with fixed frequency. [Input 5 rads] output peak at [0.01] rads. 
```Python
from random import random
from math import pi

def plot_power(data):
    angpar=np.histogram(data,bins=1000)
    FFT = np.fft.fft(angpar[0])
    deltaX = (angpar[1][-1]-angpar[1][0])/len(angpar)
    print(deltaX)
    Xrange = np.fft.fftfreq(angpar[0].size, d=deltaX)
    print(len(Xrange))
    plt.plot(Xrange[:len(Xrange)//2],(FFT*np.conj(FFT))[:len(Xrange)//2])
    plt.semilogy()
    plt.xlim(0.,np.max(Xrange))


# Create a random distribution that appears
# sinusoidal with frequency == 5 radians
x_val = np.linspace(-6,6, 1000)
def p(x):
    return np.sin(5*2*pi*x)+1
data = []
for samp in range(10000):
    for x in x_val:
        choice = 2*random()
        if choice < p(x):
            data.append(x)

plot_power(np.array(data))
```

# Fix
Suggested is to check the length to the following:

```Python
def plot_power(data,ax,axcorr=None):
	angpar=np.histogram(data,bins=400)
	FFT = np.fft.fft(angpar[0])
	deltaX = (angpar[1][-1]-angpar[1][0])/len(angpar[1]) # THIS LINE CHANGE
	Xrange = np.fft.fftfreq(angpar[0].size, d=deltaX)
	ax.plot(Xrange[:len(Xrange)/2],(FFT*np.conj(FFT))[:len(Xrange)/2])
	ax.semilogy()
	ax.set_xlim(0.,np.max(Xrange))
	if(axcorr):
		IFFT=np.fft.fftshift(np.fft.ifft(FFT*np.conj(FFT)))*deltaX
		bins=(angpar[1][1:]+angpar[1][:-1])/2.
		bins = bins-bins[len(bins)/2]
		axcorr.plot(bins,IFFT)
```

**Comment by jls713** [comment]
Hi Peter -- thanks for this. Yes, I believe you are right. That is an error and your suggestion fixes the issue. These were my own experiments on the stream-gap power spectrum that were parallel to Jo's development. The main code and the results in the paper did not depend on this code although it is good you are now finding it useful.

**Comment by PetchMa** [comment]
@jls713 thanks for the response good to know the paper did not depend on this!
